// Date: 2015/10/20 7:29:06
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package jp.plusplus.fbs.block.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBonfire extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;

    public ModelBonfire() {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(-1F, -1F, -6F, 2, 2, 8);
        Shape1.setRotationPoint(0F, 21F, -2F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0.3346075F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 0, 0);
        Shape2.addBox(-1F, -1F, -6F, 2, 2, 8);
        Shape2.setRotationPoint(-1.466667F, 23F, -1.133333F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 1.003822F, 0F);
        Shape3 = new ModelRenderer(this, 20, 0);
        Shape3.addBox(-1F, -1F, -5F, 2, 2, 7);
        Shape3.setRotationPoint(4.666667F, 23F, 4.266667F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0.8551081F, 0F);
        Shape4 = new ModelRenderer(this, 38, 0);
        Shape4.addBox(-1F, -1F, -3F, 2, 2, 6);
        Shape4.setRotationPoint(-2.866667F, 23F, 3.733333F);
        Shape4.setTextureSize(64, 32);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, -0.669215F, 0F);
        Shape5 = new ModelRenderer(this, 0, 0);
        Shape5.addBox(-1F, -1F, -4F, 2, 2, 8);
        Shape5.setRotationPoint(-3.6F, 21.26667F, -0.2666667F);
        Shape5.setTextureSize(64, 32);
        Shape5.mirror = true;
        setRotation(Shape5, 0.4833219F, 1.283798F, 0F);
        Shape6 = new ModelRenderer(this, 20, 0);
        Shape6.addBox(-1F, -1F, -3.4F, 2, 2, 7);
        Shape6.setRotationPoint(3.8F, 21.86667F, -1.866667F);
        Shape6.setTextureSize(64, 32);
        Shape6.mirror = true;
        setRotation(Shape6, -0.3346075F, 2.193538F, 0F);
        Shape7 = new ModelRenderer(this, 0, 0);
        Shape7.addBox(-1F, -1F, -5.4F, 2, 2, 8);
        Shape7.setRotationPoint(0.7333333F, 22.2F, 5.2F);
        Shape7.setTextureSize(64, 32);
        Shape7.mirror = true;
        setRotation(Shape7, -0.3346075F, 0.1115358F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

}
