// Date: 2016/04/03 9:04:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package jp.plusplus.fbs.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelHailstorm extends ModelBase {
    //fields
    ModelRenderer Shape1;

    public ModelHailstorm() {
        textureWidth = 128;
        textureHeight = 64;

        Shape1 = new ModelRenderer(this, 22, 22);
        Shape1.addBox(-4F, -4F, -4F, 8, 8, 8);
        Shape1.setRotationPoint(0F, 0F, 0F);
        Shape1.setTextureSize(128, 64);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        Shape1.render(f5);

        GL11.glPushMatrix();
        GL11.glRotatef((float) Math.PI / 4.0f, 0, 1, 0);
        GL11.glRotatef((float)Math.PI/4.0f, -1, 0, 0);
        Shape1.render(f5);
        GL11.glPopMatrix();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

}
