// Date: 2015/08/26 12:11:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package jp.plusplus.fbs.pottery.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelJarLarge extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape2b;
    ModelRenderer Shape2c;
    ModelRenderer Shape2d;
    ModelRenderer Shape3;
    ModelRenderer Shape3b;
    ModelRenderer Shape3c;
    ModelRenderer Shape3d;
    ModelRenderer Shape4;
    ModelRenderer Shape4b;
    ModelRenderer Shape4c;
    ModelRenderer Shape4d;
    ModelRenderer Shape5;
    ModelRenderer Shape5b;
    ModelRenderer Shape5c;
    ModelRenderer Shape5d;

    public ModelJarLarge() {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(-6F, 7F, -6F, 12, 1, 12);
        Shape1.setRotationPoint(0F, 16F, 0F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 36, 0);
        Shape2.addBox(-6F, 5F, -7F, 13, 2, 1);
        Shape2.setRotationPoint(0F, 16F, 0F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape2b = new ModelRenderer(this, 36, 0);
        Shape2b.addBox(-6F, 5F, -7F, 13, 2, 1);
        Shape2b.setRotationPoint(0F, 16F, 0F);
        Shape2b.setTextureSize(64, 32);
        Shape2b.mirror = true;
        setRotation(Shape2b, 0F, -1.570796F, 0F);
        Shape2c = new ModelRenderer(this, 36, 0);
        Shape2c.addBox(-6F, 5F, -7F, 13, 2, 1);
        Shape2c.setRotationPoint(0F, 16F, 0F);
        Shape2c.setTextureSize(64, 32);
        Shape2c.mirror = true;
        setRotation(Shape2c, 0F, 1.570796F, 0F);
        Shape2d = new ModelRenderer(this, 36, 0);
        Shape2d.addBox(-6F, 5F, -7F, 13, 2, 1);
        Shape2d.setRotationPoint(0F, 16F, 0F);
        Shape2d.setTextureSize(64, 32);
        Shape2d.mirror = true;
        setRotation(Shape2d, 0F, 3.141593F, 0F);
        Shape3 = new ModelRenderer(this, 0, 13);
        Shape3.addBox(-7F, -5F, -8F, 15, 10, 1);
        Shape3.setRotationPoint(0F, 16F, 0F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape3b = new ModelRenderer(this, 0, 13);
        Shape3b.addBox(-7F, -5F, -8F, 15, 10, 1);
        Shape3b.setRotationPoint(0F, 16F, 0F);
        Shape3b.setTextureSize(64, 32);
        Shape3b.mirror = true;
        setRotation(Shape3b, 0F, -1.570796F, 0F);
        Shape3c = new ModelRenderer(this, 0, 13);
        Shape3c.addBox(-7F, -5F, -8F, 15, 10, 1);
        Shape3c.setRotationPoint(0F, 16F, 0F);
        Shape3c.setTextureSize(64, 32);
        Shape3c.mirror = true;
        setRotation(Shape3c, 0F, 1.570796F, 0F);
        Shape3d = new ModelRenderer(this, 0, 13);
        Shape3d.addBox(-7F, -5F, -8F, 15, 10, 1);
        Shape3d.setRotationPoint(0F, 16F, 0F);
        Shape3d.setTextureSize(64, 32);
        Shape3d.mirror = true;
        setRotation(Shape3d, 0F, 3.141593F, 0F);
        Shape4 = new ModelRenderer(this, 36, 3);
        Shape4.addBox(-6F, -7F, -7F, 13, 2, 1);
        Shape4.setRotationPoint(0F, 16F, 0F);
        Shape4.setTextureSize(64, 32);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape4b = new ModelRenderer(this, 36, 3);
        Shape4b.addBox(-6F, -7F, -7F, 13, 2, 1);
        Shape4b.setRotationPoint(0F, 16F, 0F);
        Shape4b.setTextureSize(64, 32);
        Shape4b.mirror = true;
        setRotation(Shape4b, 0F, -1.570796F, 0F);
        Shape4c = new ModelRenderer(this, 36, 3);
        Shape4c.addBox(-6F, -7F, -7F, 13, 2, 1);
        Shape4c.setRotationPoint(0F, 16F, 0F);
        Shape4c.setTextureSize(64, 32);
        Shape4c.mirror = true;
        setRotation(Shape4c, 0F, 1.570796F, 0F);
        Shape4d = new ModelRenderer(this, 36, 3);
        Shape4d.addBox(-6F, -7F, -7F, 13, 2, 1);
        Shape4d.setRotationPoint(0F, 16F, 0F);
        Shape4d.setTextureSize(64, 32);
        Shape4d.mirror = true;
        setRotation(Shape4d, 0F, 3.141593F, 0F);
        Shape5 = new ModelRenderer(this, 30, 13);
        Shape5.addBox(-6F, -8F, -8F, 14, 1, 2);
        Shape5.setRotationPoint(0F, 16F, 0F);
        Shape5.setTextureSize(64, 32);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape5b = new ModelRenderer(this, 30, 13);
        Shape5b.addBox(-6F, -8F, -8F, 14, 1, 2);
        Shape5b.setRotationPoint(0F, 16F, 0F);
        Shape5b.setTextureSize(64, 32);
        Shape5b.mirror = true;
        setRotation(Shape5b, 0F, -1.570796F, 0F);
        Shape5c = new ModelRenderer(this, 30, 13);
        Shape5c.addBox(-6F, -8F, -8F, 14, 1, 2);
        Shape5c.setRotationPoint(0F, 16F, 0F);
        Shape5c.setTextureSize(64, 32);
        Shape5c.mirror = true;
        setRotation(Shape5c, 0F, 1.570796F, 0F);
        Shape5d = new ModelRenderer(this, 30, 13);
        Shape5d.addBox(-6F, -8F, -8F, 14, 1, 2);
        Shape5d.setRotationPoint(0F, 16F, 0F);
        Shape5d.setTextureSize(64, 32);
        Shape5d.mirror = true;
        setRotation(Shape5d, 0F, 3.141593F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape2b.render(f5);
        Shape2c.render(f5);
        Shape2d.render(f5);
        Shape3.render(f5);
        Shape3b.render(f5);
        Shape3c.render(f5);
        Shape3d.render(f5);
        Shape4.render(f5);
        Shape4b.render(f5);
        Shape4c.render(f5);
        Shape4d.render(f5);
        Shape5.render(f5);
        Shape5b.render(f5);
        Shape5c.render(f5);
        Shape5d.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

}
