// Date: 2015/08/26 21:38:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package jp.plusplus.fbs.pottery.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPotMedium extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape2b;
    ModelRenderer Shape2c;
    ModelRenderer Shape2d;
    ModelRenderer Shape3;
    ModelRenderer Shape3b;
    ModelRenderer Shape3c;
    ModelRenderer Shape3d;
    ModelRenderer Shape4;
    ModelRenderer Shape4b;
    ModelRenderer Shape4c;
    ModelRenderer Shape4d;
    ModelRenderer Shape5;
    ModelRenderer Shape5b;
    ModelRenderer Shape5c;
    ModelRenderer Shape5d;
    ModelRenderer Shape6;
    ModelRenderer Shape6b;
    ModelRenderer Shape6c;
    ModelRenderer Shape6d;
    ModelRenderer Shape7;
    ModelRenderer Shape7b;
    ModelRenderer Shape7c;
    ModelRenderer Shape7d;
    ModelRenderer Shape8;
    ModelRenderer Shape8b;
    ModelRenderer Shape8c;
    ModelRenderer Shape8d;

    public ModelPotMedium(int offY) {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 0, 0 + offY);
        Shape1.addBox(-3F, 7F, -3F, 6, 1, 6);
        Shape1.setRotationPoint(0F, 16F, 0F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 18, 0 + offY);
        Shape2.addBox(-3F, 5F, -4F, 7, 2, 1);
        Shape2.setRotationPoint(0F, 16F, 0F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape2b = new ModelRenderer(this, 18, 0 + offY);
        Shape2b.addBox(-3F, 5F, -4F, 7, 2, 1);
        Shape2b.setRotationPoint(0F, 16F, 0F);
        Shape2b.setTextureSize(64, 32);
        Shape2b.mirror = true;
        setRotation(Shape2b, 0F, -1.570796F, 0F);
        Shape2c = new ModelRenderer(this, 18, 0 + offY);
        Shape2c.addBox(-3F, 5F, -4F, 7, 2, 1);
        Shape2c.setRotationPoint(0F, 16F, 0F);
        Shape2c.setTextureSize(64, 32);
        Shape2c.mirror = true;
        setRotation(Shape2c, 0F, 1.570796F, 0F);
        Shape2d = new ModelRenderer(this, 18, 0 + offY);
        Shape2d.addBox(-3F, 5F, -4F, 7, 2, 1);
        Shape2d.setRotationPoint(0F, 16F, 0F);
        Shape2d.setTextureSize(64, 32);
        Shape2d.mirror = true;
        setRotation(Shape2d, 0F, 3.141593F, 0F);
        Shape3 = new ModelRenderer(this, 42, 5 + offY);
        Shape3.addBox(-4F, 3F, -5F, 9, 2, 1);
        Shape3.setRotationPoint(0F, 16F, 0F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape3b = new ModelRenderer(this, 42, 5 + offY);
        Shape3b.addBox(-4F, 3F, -5F, 9, 2, 1);
        Shape3b.setRotationPoint(0F, 16F, 0F);
        Shape3b.setTextureSize(64, 32);
        Shape3b.mirror = true;
        setRotation(Shape3b, 0F, -1.570796F, 0F);
        Shape3c = new ModelRenderer(this, 42, 5 + offY);
        Shape3c.addBox(-4F, 3F, -5F, 9, 2, 1);
        Shape3c.setRotationPoint(0F, 16F, 0F);
        Shape3c.setTextureSize(64, 32);
        Shape3c.mirror = true;
        setRotation(Shape3c, 0F, 1.570796F, 0F);
        Shape3d = new ModelRenderer(this, 42, 5 + offY);
        Shape3d.addBox(-4F, 3F, -5F, 9, 2, 1);
        Shape3d.setRotationPoint(0F, 16F, 0F);
        Shape3d.setTextureSize(64, 32);
        Shape3d.mirror = true;
        setRotation(Shape3d, 0F, 3.141593F, 0F);
        Shape4 = new ModelRenderer(this, 34, 0 + offY);
        Shape4.addBox(-5F, -1F, -6F, 11, 4, 1);
        Shape4.setRotationPoint(0F, 16F, 0F);
        Shape4.setTextureSize(64, 32);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape4b = new ModelRenderer(this, 34, 0 + offY);
        Shape4b.addBox(-5F, -1F, -6F, 11, 4, 1);
        Shape4b.setRotationPoint(0F, 16F, 0F);
        Shape4b.setTextureSize(64, 32);
        Shape4b.mirror = true;
        setRotation(Shape4b, 0F, -1.570796F, 0F);
        Shape4c = new ModelRenderer(this, 34, 0 + offY);
        Shape4c.addBox(-5F, -1F, -6F, 11, 4, 1);
        Shape4c.setRotationPoint(0F, 16F, 0F);
        Shape4c.setTextureSize(64, 32);
        Shape4c.mirror = true;
        setRotation(Shape4c, 0F, 1.570796F, 0F);
        Shape4d = new ModelRenderer(this, 34, 0 + offY);
        Shape4d.addBox(-5F, -1F, -6F, 11, 4, 1);
        Shape4d.setRotationPoint(0F, 16F, 0F);
        Shape4d.setTextureSize(64, 32);
        Shape4d.mirror = true;
        setRotation(Shape4d, 0F, 3.141593F, 0F);
        Shape5 = new ModelRenderer(this, 16, 7 + offY);
        Shape5.addBox(-4F, -2F, -5F, 9, 1, 1);
        Shape5.setRotationPoint(0F, 16F, 0F);
        Shape5.setTextureSize(64, 32);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape5b = new ModelRenderer(this, 16, 7 + offY);
        Shape5b.addBox(-4F, -2F, -5F, 9, 1, 1);
        Shape5b.setRotationPoint(0F, 16F, 0F);
        Shape5b.setTextureSize(64, 32);
        Shape5b.mirror = true;
        setRotation(Shape5b, 0F, -1.570796F, 0F);
        Shape5c = new ModelRenderer(this, 16, 7 + offY);
        Shape5c.addBox(-4F, -2F, -5F, 9, 1, 1);
        Shape5c.setRotationPoint(0F, 16F, 0F);
        Shape5c.setTextureSize(64, 32);
        Shape5c.mirror = true;
        setRotation(Shape5c, 0F, 1.570796F, 0F);
        Shape5d = new ModelRenderer(this, 16, 7 + offY);
        Shape5d.addBox(-4F, -2F, -5F, 9, 1, 1);
        Shape5d.setRotationPoint(0F, 16F, 0F);
        Shape5d.setTextureSize(64, 32);
        Shape5d.mirror = true;
        setRotation(Shape5d, 0F, 3.141593F, 0F);
        Shape6 = new ModelRenderer(this, 0, 7 + offY);
        Shape6.addBox(-3F, -3F, -4F, 7, 1, 1);
        Shape6.setRotationPoint(0F, 16F, 0F);
        Shape6.setTextureSize(64, 32);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape6b = new ModelRenderer(this, 0, 7 + offY);
        Shape6b.addBox(-3F, -3F, -4F, 7, 1, 1);
        Shape6b.setRotationPoint(0F, 16F, 0F);
        Shape6b.setTextureSize(64, 32);
        Shape6b.mirror = true;
        setRotation(Shape6b, 0F, -1.570796F, 0F);
        Shape6c = new ModelRenderer(this, 0, 7 + offY);
        Shape6c.addBox(-3F, -3F, -4F, 7, 1, 1);
        Shape6c.setRotationPoint(0F, 16F, 0F);
        Shape6c.setTextureSize(64, 32);
        Shape6c.mirror = true;
        setRotation(Shape6c, 0F, 1.570796F, 0F);
        Shape6d = new ModelRenderer(this, 0, 7 + offY);
        Shape6d.addBox(-3F, -3F, -4F, 7, 1, 1);
        Shape6d.setRotationPoint(0F, 16F, 0F);
        Shape6d.setTextureSize(64, 32);
        Shape6d.mirror = true;
        setRotation(Shape6d, 0F, 3.141593F, 0F);
        Shape7 = new ModelRenderer(this, 18, 3 + offY);
        Shape7.addBox(-2F, -4F, -3F, 5, 1, 1);
        Shape7.setRotationPoint(0F, 16F, 0F);
        Shape7.setTextureSize(64, 32);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape7b = new ModelRenderer(this, 18, 3 + offY);
        Shape7b.addBox(-2F, -4F, -3F, 5, 1, 1);
        Shape7b.setRotationPoint(0F, 16F, 0F);
        Shape7b.setTextureSize(64, 32);
        Shape7b.mirror = true;
        setRotation(Shape7b, 0F, -1.570796F, 0F);
        Shape7c = new ModelRenderer(this, 18, 3 + offY);
        Shape7c.addBox(-2F, -4F, -3F, 5, 1, 1);
        Shape7c.setRotationPoint(0F, 16F, 0F);
        Shape7c.setTextureSize(64, 32);
        Shape7c.mirror = true;
        setRotation(Shape7c, 0F, 1.570796F, 0F);
        Shape7d = new ModelRenderer(this, 18, 3 + offY);
        Shape7d.addBox(-2F, -4F, -3F, 5, 1, 1);
        Shape7d.setRotationPoint(0F, 16F, 0F);
        Shape7d.setTextureSize(64, 32);
        Shape7d.mirror = true;
        setRotation(Shape7d, 0F, 3.141593F, 0F);
        Shape8 = new ModelRenderer(this, 24, 5 + offY);
        Shape8.addBox(-3F, -5F, -4F, 7, 1, 1);
        Shape8.setRotationPoint(0F, 16F, 0F);
        Shape8.setTextureSize(64, 32);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
        Shape8b = new ModelRenderer(this, 24, 5 + offY);
        Shape8b.addBox(-3F, -5F, -4F, 7, 1, 1);
        Shape8b.setRotationPoint(0F, 16F, 0F);
        Shape8b.setTextureSize(64, 32);
        Shape8b.mirror = true;
        setRotation(Shape8b, 0F, -1.570796F, 0F);
        Shape8c = new ModelRenderer(this, 24, 5 + offY);
        Shape8c.addBox(-3F, -5F, -4F, 7, 1, 1);
        Shape8c.setRotationPoint(0F, 16F, 0F);
        Shape8c.setTextureSize(64, 32);
        Shape8c.mirror = true;
        setRotation(Shape8c, 0F, 1.570796F, 0F);
        Shape8d = new ModelRenderer(this, 24, 5 + offY);
        Shape8d.addBox(-3F, -5F, -4F, 7, 1, 1);
        Shape8d.setRotationPoint(0F, 16F, 0F);
        Shape8d.setTextureSize(64, 32);
        Shape8d.mirror = true;
        setRotation(Shape8d, 0F, 3.141593F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape2b.render(f5);
        Shape2c.render(f5);
        Shape2d.render(f5);
        Shape3.render(f5);
        Shape3b.render(f5);
        Shape3c.render(f5);
        Shape3d.render(f5);
        Shape4.render(f5);
        Shape4b.render(f5);
        Shape4c.render(f5);
        Shape4d.render(f5);
        Shape5.render(f5);
        Shape5b.render(f5);
        Shape5c.render(f5);
        Shape5d.render(f5);
        Shape6.render(f5);
        Shape6b.render(f5);
        Shape6c.render(f5);
        Shape6d.render(f5);
        Shape7.render(f5);
        Shape7b.render(f5);
        Shape7c.render(f5);
        Shape7d.render(f5);
        Shape8.render(f5);
        Shape8b.render(f5);
        Shape8c.render(f5);
        Shape8d.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

}
